// Code generated by 'yaegi extract github.com/overflow0verture/proxy_harvester/internal/requests'. DO NOT EDIT.

package symbols

import (
	"github.com/overflow0verture/proxy_harvester/internal/requests"
	"reflect"
)

func init() {
	Symbols["github.com/overflow0verture/proxy_harvester/internal/requests/requests"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Delete":       reflect.ValueOf(requests.Delete),
		"Get":          reflect.ValueOf(requests.Get),
		"Head":         reflect.ValueOf(requests.Head),
		"InitRequests": reflect.ValueOf(requests.InitRequests),
		"NewSession":   reflect.ValueOf(requests.NewSession),
		"Post":         reflect.ValueOf(requests.Post),
		"Put":          reflect.ValueOf(requests.Put),

		// type definitions
		"RequestOptions": reflect.ValueOf((*requests.RequestOptions)(nil)),
		"Response":       reflect.ValueOf((*requests.Response)(nil)),
		"Session":        reflect.ValueOf((*requests.Session)(nil)),
	}
}
