[listener]
IP='127.0.0.1'
PORT=10086
userName=''
password=''

[task]
periodicChecking='0 */5 * * *'


[checkSocks]#******非特殊情况，默认即可******
#通过访问实际url来验证代理的可用性
checkURL='https://www.baidu.com/robots.txt'#可以配置为要访问的目标地址，确保所有代理都能访问到目标地址
checkRspKeywords='Baiduspider'#上面地址原始响应中的某个字符串，用来验证通过代理访问目标时有无因某种原因被ban掉。
maxConcurrentReq=200 #同时最多N个并发通过代理访问上面的地址，检测socks5代理是否可用，可根据网络环境调整。云主机的话开500、1000都可以，本机的话，开三五十差不多。
timeout=6 #单位秒，验证socks5代理的超时时间,建议保持在5或6，检查及使用代理访问上面的地址时，超过这个时间，判定无效

[checkSocks.checkGeolocate]##******非特殊情况，默认即可******通过访问返回IP归属地信息的URL和关键字判断，来排除某些代理，如：某些情况下，真正要访问的系统限制只有大陆地区IP可以访问
switch='close' #open:启用，非open:禁用
checkURL='https://qifu-api.baidubce.com/ip/local/geo/v1/district'#访问此url获取IP归属地信息，出于某些原因，建议用国内的公司的相关接口。
#下面的两个的值，需要根据上面url的返回内容填写
excludeKeywords=['澳门','香港','台湾']#格式如：['澳门','香港']优先级最高，返回的body内容中，存在任一关键字，则跳过，
includeKeywords=['中国']#格式如：['中国','北京']则只获取中国北京的代理，如果是['中国'],排除上述关键字的前提下则获取中国所有其他地区代理

[storage]
type = "file"                    # 可选 file 或 redis
file_name = "ProxyData.txt"
#type = "redis"
#redis_host = "127.0.0.1"
#redis_port = 6379
#redis_password = ""


[plugin]
plugin_folder = "plugins"

[log]
enabled = true                # 是否启用日志文件
log_dir = "log"               # 日志文件存放目录
ip_summary_interval = 5       # IP汇总间隔（分钟）


[apiserver]
switch = 'open'           # 开启API服务器 (open/close)
token = "atoken"          # API访问令牌
port = 10087              # 服务端口